### ISSUE TITLE
Ubuntu 14.04LTS Sparkleshare hangs after latest update

### ISSUE THREAD

**Issue by rob-hills** [hbons/SparkleShare#1606]
I updated Sparkleshare to 1.4.0 last night after being notified of an update via the Ubuntu APT repository system.  On starting my computer today, I noticed the Sparkleshare icon was missing from the top of the screen so I tried to start it manually:
```
~$ sparkleshare start
```
Which resulted in it hanging with the following stack trace:
```
~$ 10:54:17 | Environment | SparkleShare version: 1.4.0, Operating system: Unix (Unix 3.13.0.44)
10:54:17 | Auth | The following keys may be used:

Marshaling activate signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.WebView ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMAttr ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMNode ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMObject ---> System.DllNotFoundException: libwebkitgtksharpglue-1.10.2.so
  at (wrapper managed-to-native) WebKit.DOMObject:webkitsharp_webkit_domobject_get_parentInstance_offset ()
  at WebKit.DOMObject..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMNode..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMAttr..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GtkSharp.WebkitgtkSharp.ObjectManager.Initialize () [0x00000] in <filename unknown>:0 
  at WebKit.WebView..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at SparkleShare.SparkleEventLog..ctor () [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleUI.ApplicationActivatedDelegate (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.MarshalCallback (IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.g_application_run(IntPtr , Int32 , IntPtr )
   at GLib.Application.Run(Int32 argc, System.String argv)
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(System.String[] args)
```

**Comment by hbons** [comment]
this looks like a packaging problem where it can't find Webkit. you probably want to file this against Ubuntu.

**Comment by hbons** [comment]
are you using a PPA to get the SparkleShare package? Ubuntu isn't quite on 1.4 yet.

**Comment by rob-hills** [comment]
Hi,
Yes, I am using [Thanh Tung Nguyen's "Unofficial" Sparkleshare PPA](https://launchpad.net/~rebuntu16/+archive/ubuntu/sparkleshare+unofficial), the only one I've been able to find that will keep me up with the latest Stable release.
I see on the above website that he recommends that "Users should replace libwebkitgtk3.0-cil or libwebkitgtk1.10-cil by libwebkitgtk2.0-cil".

I have libwebkitgtk2.0-cil installed however it is flagged as no longer required:
```
The following package was automatically installed and is no longer required:
  libwebkitgtk2.0-cil
```
Not sure why.  Given his warning, surely Mr Nguyen's PPA shouldn't be causing this?

**Comment by hbons** [comment]
i actually don't know anything about packaging. it's best to contact them about the issue.
i do think it has something to do with the PPA, as i've received three reports about it today already.
