### ISSUE TITLE
sparkleshare wont start

### ISSUE THREAD

**Issue by jubalh** [hbons/SparkleShare#1630]
Hello there,
installing sparkleshare on another computer I get this: https://bpaste.net/show/9eafb9040085

user@linux-bzmo ~ % sparkleshare start
user@linux-bzmo ~ % 11:30:42 | Environment | SparkleShare version: 1.4.0, Operating system: Unix (Unix 4.0.4.3)
11:30:43 | Config | Wrote to '/home/user/.config/sparkleshare/config.xml'
11:30:43 | Config | Updated option notifications:True

(mono:16773): GLib-GObject-WARNING **: The property GtkMisc:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
Marshaling activate signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.WebView ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMAttr ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for WebKit.DOMNode ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: libwebkitgtk-3.0.so.0
  at (wrapper managed-to-native) WebKit.DOMObject:webkit_dom_object_get_type ()
  at WebKit.DOMObject.get_GType () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) System.Reflection.MonoProperty/StaticGetter`1<GLib.GType>:invoke_R ()
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType] (System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMNode..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.StaticGetterAdapterFrame[GType](System.Reflection.StaticGetter`1 getter, System.Object obj) [0x00000] in <filename unknown>:0 
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) [0x00000] in <filename unknown>:0 
  at GLib.GType.LookupGObjectType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.Object.LookupGType (System.Type t) [0x00000] in <filename unknown>:0 
  at GLib.GType.op_Explicit (System.Type type) [0x00000] in <filename unknown>:0 
  at WebKit.DOMAttr..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at GtkSharp.WebkitgtkSharp.ObjectManager.Initialize () [0x00000] in <filename unknown>:0 
  at WebKit.WebView..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at SparkleShare.SparkleEventLog..ctor () [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleUI.ApplicationActivatedDelegate (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.MarshalCallback (IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.g_application_run(IntPtr , Int32 , IntPtr )
   at GLib.Application.Run(Int32 argc, System.String argv)
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(System.String[] args)

**Comment by hbons** [comment]
Looks like it can't find Webkit. Have you installed webkitgtk-sharp? https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Linux/README.md

**Comment by jubalh** [comment]
hmm strange i installed it via package manager. if thats really the case then the package needs fixing. thanks for the hint @hbons i will take a look at it tomorrow and notice my distributions package manager :)

**Comment by jubalh** [comment]
S | Name                     | Zusammenfassung                                     | Typ  
--+--------------------------+-----------------------------------------------------+------
i | libwebkitgtk-1_0-0       | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk-1_0-0-32bit | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk-3_0-0       | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk-3_0-0-32bit | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk-devel       | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk2-lang       | Languages for package webkitgtk                     | Paket
  | libwebkitgtk3-devel      | Library for rendering web content, GTK+ Port        | Paket
  | libwebkitgtk3-lang       | Languages for package webkitgtk3                    | Paket
  | python-webkitgtk         | Python bindings for WebKit/Gtk                      | Paket
  | python-webkitgtk-devel   | Python bindings for WebKit/Gtk -- Development Files | Paket
i | webkitgtk-sharp          | WebKitGTK bindings for Mono                         | Paket
  | webkitgtk-sharp-devel    | WebKitGTK bindings for Mono -- Development files    | Paket

webkitgtk-sharp seems to be installed.

**Comment by jubalh** [comment]
Any other idea?

**Comment by hbons** [comment]
This will be fixed with flatpak apps.

**Comment by jubalh** [comment]
Distributions will still package it. And this should also be supported.

**Comment by hbons** [comment]
True, but this is the whole reason I'm moving to flatpaks: I can't check all the distro packaging. I'd file a bug with your distro because this package seems broken.

**Comment by jubalh** [comment]
I am trying to fix it for this distro ;)
But then I inded up not knowing enough about SparkleShare so I came here to ask :)

**Comment by hbons** [comment]
Ok. :) File it there and let me know if there's any issues.
