### ISSUE TITLE
Sparkle Share Crashed

### ISSUE THREAD

**Issue by tparadela** [hbons/SparkleShare#1653]
It gave me this code. Please help.

SparkleShare version: 1.4.0
Operating system:     Win32NT (Microsoft Windows NT 6.2.9200.0)
System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SparkleShare.SparkleController.StartSSH()
   at SparkleShare.SparkleController.Initialize()
   at SparkleShare.Program.Main(String[] args)

**Comment by andrewbates09** [comment]
@tparadela is there any more to your crash report?

Here's the crash report I received:
```
SparkleShare version: 1.5.0
Operating system:     Win32NT (Microsoft Windows NT 6.2.9200.0)
System.ArgumentNullException: Value cannot be null.
Parameter name: data
   at System.Windows.Clipboard.SetData(String format, Object data)
   at SparkleShare.SparkleController.CopyToClipboard(String text)
   at SparkleShare.SparkleSetupController.CopyToClipboardClicked()
   at SparkleShare.SparkleSetup.<>c__DisplayClass81.<.ctor>b__7d(Object param0, RoutedEventArgs param1)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run()
   at SparkleShare.Program.Main(String[] args)
17:36:27 | Controller | ssh-agent started, PID=4868
17:36:27 | Environment | SparkleShare version: 1.5.0, Operating system: Win32NT (Microsoft Windows NT 6.2.9200.0)
17:36:27 | Config | Wrote to 'C:\Users\%USERNAME%\AppData\Roaming\sparkleshare\config.xml'
17:36:27 | Config | Updated option notifications:True
17:36:31 | Avatars | Error fetching avatar for unknown: The remote server returned an error: (404) Not Found.    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadData(Uri address)
   at System.Net.WebClient.DownloadData(String address)
   at SparkleShare.SparkleAvatars.GetAvatar(String email, Int32 size, String target_path)
17:36:44 | Config | Wrote to 'C:\Users\%USERNAME%\AppData\Roaming\sparkleshare\config.xml'
```

**Comment by leonyu** [comment]
I just had the `Value cannot be null` problem. It was caused by the fact that I deleted the `known_hosts` file in ssh folder.

**Comment by hbons** [comment]
These are all different issues. :)
@leonyu yours has been fixed. SparkleShare will keep its own SSH configuration in the next version.

**Comment by hbons** [comment]
Actually, the original will have been fixed too. :)
