### ISSUE TITLE
SparkleShare doesn't start on Xubuntu 15.10

### ISSUE THREAD

**Issue by mlanner** [hbons/SparkleShare#1674]
Installed SparkleShare from PPA on Xubuntu 15.10 but it seems to fail at this time. Specifically, here's the output when trying to start it from CLI:

```
11:16:22 | Environment | SparkleShare version: 1.4.0, Operating system: Unix (Unix 4.2.0.22)
11:16:23 | Config | Wrote to '/home/mlanner/.config/sparkleshare/config.xml'
11:16:23 | Config | Updated option notifications:True
Marshaling activate signal
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: An exception was thrown by the type initializer for AppIndicator3.Indicator ---> System.DllNotFoundException: appindicator3-sharp.dll
  at (wrapper managed-to-native) AppIndicator3.Indicator:app_indicator_get_type ()
  at AppIndicator3.Indicator.get_GType () [0x00000] in <filename unknown>:0 
  at GtkSharp.Appindicator3Sharp.ObjectManager.Initialize () [0x00000] in <filename unknown>:0 
  at AppIndicator3.Indicator..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at SparkleShare.SparkleStatusIcon..ctor () [0x00000] in <filename unknown>:0 
  at SparkleShare.SparkleUI.ApplicationActivatedDelegate (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <filename unknown>:0 
  at GLib.Signal.ClosureInvokedCB (System.Object o, GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.Invoke (GLib.ClosureInvokedArgs args) [0x00000] in <filename unknown>:0 
  at GLib.SignalClosure.MarshalCallback (IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data) [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
   at GLib.Application.g_application_run(IntPtr , Int32 , IntPtr )
   at GLib.Application.Run(Int32 argc, System.String argv)
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(System.String[] args)
```

I also looked at installing from source, but it appears that the documentation at https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Linux/README.md is a bit dated. I'd like to get SparkleShare running on newer versions of Ubuntu, including Xubuntu. I'd be happy to document the process, but I'm unsure of the dependencies.

What is the preferred install method on Linux, running the `install-sh` or `configure`, `make`, `make install`?

**Comment by hbons** [comment]
It seems like the appindicator bindings can't be found.
I think this is an issue with the packaging in the PPA?

**Comment by hbons** [comment]
Closing this as I think it's a packaging or distro issue.
