### ISSUE TITLE
SIGSEGV in Gtk on ArchLinux

### ISSUE THREAD

**Issue by lubosz** [hbons/SparkleShare#1682]
I get following native crash which seems to be related to Gtk.Label.
Tested with 1.5 and git master, same result.

Related package versions:
gtk 3.18.8
glib 2.46.2
gtk-sharp 2.99.3 (also tried git master, same)
mono 4.2.2.30

```
$ ./bin/SparkleShare.exe
12:48:55 | Environment | SparkleShare version: 1.5.0, Operating system: Unix (Unix 4.4.2.1)

(process:1631): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:1631): GLib-GObject-CRITICAL **: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Gtk.Label.gtk_label_new_with_mnemonic (intptr) <0xffffffff>
  at Gtk.Label..ctor (string) <0x00183>
  at Gtk.Label..ctor () <0x0000f>
  at SparkleShare.SparkleUI..ctor () <0x0014b>
  at SparkleShare.Program.Main (string[]) <0x004d7>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

    /usr/bin/mono() [0x4a101f]
    /usr/bin/mono() [0x4f4a4e]
    /usr/bin/mono() [0x4274b9]
    /usr/lib/libpthread.so.0(+0x10e80) [0x7fa57aac5e80]
    /usr/lib/libgtk-3.so.0(+0x2ba279) [0x7fa571be6279]
    /usr/lib/libgtk-3.so.0(+0x1693c8) [0x7fa571a953c8]
    /usr/lib/libgtk-3.so.0(+0x17d023) [0x7fa571aa9023]
    /usr/lib/libgtk-3.so.0(+0x16a71c) [0x7fa571a9671c]
    /usr/lib/libgtk-3.so.0(+0x17cf19) [0x7fa571aa8f19]
    /usr/lib/libgtk-3.so.0(+0x17cfb4) [0x7fa571aa8fb4]
    /usr/lib/libgtk-3.so.0(+0x16b292) [0x7fa571a97292]
    /usr/lib/libgobject-2.0.so.0(g_type_create_instance+0x1b7) [0x7fa5733bf2e7]
    /usr/lib/libgobject-2.0.so.0(+0x152bb) [0x7fa5733a12bb]
    /usr/lib/libgobject-2.0.so.0(g_object_newv+0xd1) [0x7fa5733a2ba1]
    /usr/lib/libgobject-2.0.so.0(g_object_new+0x104) [0x7fa5733a34d4]
    /usr/lib/libgtk-3.so.0(+0x18503a) [0x7fa571ab103a]
    /usr/lib/libgtk-3.so.0(+0x34dacc) [0x7fa571c79acc]
    /usr/lib/libgobject-2.0.so.0(g_type_create_instance+0x1b7) [0x7fa5733bf2e7]
    /usr/lib/libgobject-2.0.so.0(+0x152bb) [0x7fa5733a12bb]
    /usr/lib/libgobject-2.0.so.0(g_object_newv+0xd1) [0x7fa5733a2ba1]
    /usr/lib/libgobject-2.0.so.0(g_object_new+0x104) [0x7fa5733a34d4]
    /usr/lib/libgtk-3.so.0(gtk_label_new_with_mnemonic+0x19) [0x7fa571b29429]
    [0x4058c8d0]

Debug info from gdb:

warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
    add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/bmonkey/.gdbinit".
To completely disable this security protection add
    set auto-load safe-path /
line to your configuration file "/home/bmonkey/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
    info "(gdb)Auto-loading safe path"
[New LWP 1732]
[New LWP 1731]
[New LWP 1682]
[New LWP 1645]
[New LWP 1632]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fa57aac5adb in waitpid () from /usr/lib/libpthread.so.0
  Id   Target Id         Frame 
* 1    Thread 0x7fa57b5cb780 (LWP 1631) "SparkleShare.ex" 0x00007fa57aac5adb in waitpid () from /usr/lib/libpthread.so.0
  2    Thread 0x7fa55ffff700 (LWP 1732) "gdbus" 0x00007fa57a7f2c3d in poll () from /usr/lib/libc.so.6
  3    Thread 0x7fa564bfb700 (LWP 1731) "gmain" 0x00007fa57a7f2c3d in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fa5739ff700 (LWP 1682) "SparkleShare.ex" 0x00007fa57a7eec0d in read () from /usr/lib/libc.so.6
  5    Thread 0x7fa57a62f700 (LWP 1645) "Finalizer" 0x00007fa57aac4427 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  6    Thread 0x7fa579fff700 (LWP 1632) "SparkleShare.ex" 0x00007fa57aac203f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0

Thread 6 (Thread 0x7fa579fff700 (LWP 1632)):
#0  0x00007fa57aac203f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00000000005ff10b in ?? ()
#2  0x00007fa57aabc424 in start_thread () from /usr/lib/libpthread.so.0
#3  0x00007fa57a7fbcbd in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fa57a62f700 (LWP 1645)):
#0  0x00007fa57aac4427 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
#1  0x00007fa57aac44d4 in __new_sem_wait_slow.constprop.0 () from /usr/lib/libpthread.so.0
#2  0x0000000000624226 in mono_sem_wait ()
#3  0x00000000005a6b22 in ?? ()
#4  0x0000000000588d59 in ?? ()
#5  0x000000000062ae7c in ?? ()
#6  0x00007fa57aabc424 in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007fa57a7fbcbd in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fa5739ff700 (LWP 1682)):
#0  0x00007fa57a7eec0d in read () from /usr/lib/libc.so.6
#1  0x0000000040580c35 in ?? ()
#2  0x00007fa56c001900 in ?? ()
#3  0x00007fa57a0587d8 in ?? ()
#4  0x00007fa57a05a7a0 in ?? ()
#5  0x00007fa57a0587d8 in ?? ()
#6  0x00007fa57a058738 in ?? ()
#7  0x00007fa56c000e00 in ?? ()
#8  0x0000000040580bb0 in ?? ()
#9  0x00007fa5739fe8a0 in ?? ()
#10 0x00007fa5739fe7e0 in ?? ()
#11 0x0000000040580bb0 in ?? ()
#12 0x00007fa57a05a7c0 in ?? ()
#13 0x0000000040580aa0 in ?? ()
#14 0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7fa564bfb700 (LWP 1731)):
#0  0x00007fa57a7f2c3d in poll () from /usr/lib/libc.so.6
#1  0x00007fa5730c7f7c in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007fa5730c808c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007fa5730c80c9 in ?? () from /usr/lib/libglib-2.0.so.0
#4  0x00007fa5730ee795 in ?? () from /usr/lib/libglib-2.0.so.0
#5  0x00007fa57aabc424 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fa57a7fbcbd in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fa55ffff700 (LWP 1732)):
#0  0x00007fa57a7f2c3d in poll () from /usr/lib/libc.so.6
#1  0x00007fa5730c7f7c in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007fa5730c8302 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#3  0x00007fa572966186 in ?? () from /usr/lib/libgio-2.0.so.0
#4  0x00007fa5730ee795 in ?? () from /usr/lib/libglib-2.0.so.0
#5  0x00007fa57aabc424 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007fa57a7fbcbd in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7fa57b5cb780 (LWP 1631)):
#0  0x00007fa57aac5adb in waitpid () from /usr/lib/libpthread.so.0
#1  0x00000000004a10f6 in ?? ()
#2  0x00000000004f4a4e in ?? ()
#3  0x00000000004274b9 in ?? ()
#4  <signal handler called>
#5  0x00007fa571be6279 in ?? () from /usr/lib/libgtk-3.so.0
#6  0x00007fa571a953c8 in ?? () from /usr/lib/libgtk-3.so.0
#7  0x00007fa571aa9023 in ?? () from /usr/lib/libgtk-3.so.0
#8  0x00007fa571a9671c in ?? () from /usr/lib/libgtk-3.so.0
#9  0x00007fa571aa8f19 in ?? () from /usr/lib/libgtk-3.so.0
#10 0x00007fa571aa8fb4 in ?? () from /usr/lib/libgtk-3.so.0
#11 0x00007fa571a97292 in ?? () from /usr/lib/libgtk-3.so.0
#12 0x00007fa5733bf2e7 in g_type_create_instance () from /usr/lib/libgobject-2.0.so.0
#13 0x00007fa5733a12bb in ?? () from /usr/lib/libgobject-2.0.so.0
#14 0x00007fa5733a2ba1 in g_object_newv () from /usr/lib/libgobject-2.0.so.0
#15 0x00007fa5733a34d4 in g_object_new () from /usr/lib/libgobject-2.0.so.0
#16 0x00007fa571ab103a in ?? () from /usr/lib/libgtk-3.so.0
#17 0x00007fa571c79acc in ?? () from /usr/lib/libgtk-3.so.0
#18 0x00007fa5733bf2e7 in g_type_create_instance () from /usr/lib/libgobject-2.0.so.0
#19 0x00007fa5733a12bb in ?? () from /usr/lib/libgobject-2.0.so.0
#20 0x00007fa5733a2ba1 in g_object_newv () from /usr/lib/libgobject-2.0.so.0
#21 0x00007fa5733a34d4 in g_object_new () from /usr/lib/libgobject-2.0.so.0
#22 0x00007fa571b29429 in gtk_label_new_with_mnemonic () from /usr/lib/libgtk-3.so.0
#23 0x000000004058c8d0 in ?? ()
#24 0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted (core dumped)

```

**Comment by lubosz** [comment]
The error occurred when SparkleShare was already running and I tried to start another instance.
An error message would be nicer than a segfault though.

**Comment by kevincox** [comment]
This should probably be reopened. It is still occurring and a segfault is not a proper user experience.

**Comment by hbons** [comment]
This looks like the same as #1778?
