### ISSUE TITLE
git commit "filename too long" on Windows - sync fails

### ISSUE THREAD

**Issue by gerhard-tinned** [hbons/SparkleShare#1744]
One of my clients is running SparkleShare on Windows. He reported recently problems with files that "don't sync" when copied into the SparkleShare folder. 

The logfile revealed the following error message:
<pre>
08:19:06 | Cmd | ShareName | git commit --all --message="...list of file names ..."
08:19:06 | Cmd | Couldn't execute command: Der Dateiname oder die Erweiterung ist zu lang
</pre>

As this message is in German (German Windows version), here is my translation:

<pre>
08:19:06 | Cmd | ShareName | git commit --all --message="...list of file names ..."08:19:06 | Cmd | Couldn't execute command: The filename or the file extension is too long
</pre>

I have found a few notes on this issue. First, it seems to be a problem only on windows. It seems to effect the way git is compiled for/with the msys. See the links below.

https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
https://github.com/msysgit/git/pull/110
https://github.com/msysgit/msysgit/issues/52

From a quick look, it seems a fix has been provided about a year ago already. I was wondering if a new version with the fix could be released as a fix for my clients.

Thanks.

**Comment by hbons** [comment]
Yes, this is a known issue, but I didn't know there was a fix now. I'll try to include the fix in the next version. Meanwhile, if anyone can test that new git for Windows version that would be really helpful.

**Comment by gerhard-tinned** [comment]
Can you tell me how I can replace the git version on an already installed sparkleshare? 

Please tell me as well which version of git you are planning to use so I can test exactly that version. (maybe provide a download link)

**Comment by hbons** [comment]
@gerhard-tinned should be in Program Files\SparkleShare\git? Just replace the whole folder with your Git copy.

**Comment by gerhard-tinned** [comment]
Seems not to be that easy. Maybe i did something wrong?

1. In the sparkleshare programm directory I found a folder called "msysgit". 
2. I installed in the system the git-scm.org version.
3. I copied from the git-scm installation directory the "mingw64" directory as "msysgit" to the sparkleshare directory. 

<pre>
SparkleShare version: 1.4.0
Operating system:     Win32NT (Microsoft Windows NT 6.2.9200.0)
System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SparkleShare.SparkleController.StartSSH()
   at SparkleShare.SparkleController.Initialize()
   at SparkleShare.Program.Main(String[] args)
</pre>

**Comment by gerhard-tinned** [comment]
As it seems, it only works with the msysgit version 1.x but not with the version 2. The version 1.x seems to be outdated or not developed any more.

I am trying version Git-1.9.5-preview20150319 at the moment. 

Side effect, up-to-date ciphers are finally supported.

**Comment by gerhard-tinned** [comment]
the msys git version "Git-1.9.5-preview20150319" could be added without any problems. The new version of git allowed to use the currently suggested ssh options while the SparkleShare 1.4 delivered version is not supporting the suggested secure ssh configuration.

As of this, a new version with the Git-1.9.5-preview20150319 should be published anyway. 

I am still trying to verify the loong file/path names which i could not reproduce in a VM for testing. But I am about to test it on the PC it was reported on. I will provide an update hopefully soon. 

Never the less, please consider publishing a new version with the updated git version anyway.

**Comment by gerhard-tinned** [comment]
@hbons, can you create a new build with the latest git version?

**Comment by hbons** [comment]
@gerhard-tinned I don't have a Windows box at the moment. Also Windows in master is currently broken due to build system changes, but I'll look into that soon. :)

**Comment by gerhard-tinned** [comment]
@hbons I also do not have a Windows machine. I used Virtualbox and downloaded a ready to use VM package directly from Microsoft.

**Comment by gerhard-tinned** [comment]
How can I help?

**Comment by hbons** [comment]
@BarryThePenguin could you test this new msysgit version on Windows?

**Comment by romanshutsman** [comment]
try this `git config --system core.longpaths true`

**Comment by hbons** [comment]
@romanshutsman Nice. Looks like this is a new setting? I'll add this to the default Git config in SparkleShare.

**Comment by romanshutsman** [comment]
no, it is available from v1.9.0 (2014)

**Comment by romanshutsman** [comment]
@hbons no, it is available from v1.9.0 (2014)

**Comment by hbons** [comment]
@romanshutsman I see. It's not documented anywhere on the official website so I missed that...

**Comment by hbons** [comment]
Closing all Windows issues for now as I'm working on a SparkleShare rewrite in Rust: https://github.com/hbons/Twinkle.

If you like this work and want to support development, I’m looking for sponsors since I’m currently jobless: https://github.com/sponsors/hbons.
