### ISSUE TITLE
Sparkleshare has crashed

### ISSUE THREAD

**Issue by dgantkendricks** [hbons/SparkleShare#1764]
------

SparkleShare version: 1.4.0
Operating system:     Win32NT (Microsoft Windows NT 6.2.9200.0)
System.NullReferenceException: Object reference not set to an instance of an object.
   at SparkleShare.SparkleControllerBase.StopFetcher()
   at SparkleShare.SparkleSetupController.SyncingCancelled()
   at SparkleShare.SparkleSetup.<>c__DisplayClass81.<.ctor>b__62(Object , RoutedEventArgs )
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run()
   at SparkleShare.SparkleUI.Run()
   at SparkleShare.Program.Main(String[] args)

22:02:59 | Cmd | COMP150-SP17-PSA2-Group5 | git rev-parse HEAD

22:02:59 | Cmd | COMP150-SP17-PSA2-Group5 | git ls-remote --heads --exit-code "ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA2-Group5" master

22:02:59 | Git | COMP150-SP17-PSA1-Group5 | Checking for remote changes...

22:02:59 | Cmd | COMP150-SP17-PSA1-Group5 | git rev-parse HEAD

22:02:59 | Cmd | COMP150-SP17-PSA1-Group5 | git ls-remote --heads --exit-code "ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA1-Group5" master

22:03:00 | Git | COMP150-SP17-PSA0 | Checking for remote changes...

22:03:00 | Cmd | COMP150-SP17-PSA0 | git rev-parse HEAD

22:03:00 | Cmd | COMP150-SP17-PSA0 | git ls-remote --heads --exit-code "ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA0" master

22:03:01 | Git | COMP150-SP17-PSA3-Group5 | Checking for remote changes...

22:03:01 | Cmd | COMP150-SP17-PSA3-Group5 | git rev-parse HEAD

22:03:01 | Cmd | COMP150-SP17-PSA3-Group5 | git ls-remote --heads --exit-code "ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA3-Group5" master

22:03:54 | Listener | Trying to reconnect to tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Subscribing to channel 5a0f17b1e6ad70ce6e86c05dc2bb5b4b0b890efc on tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Subscribing to channel 290b412e03a7a0c59901b795f3622e7e5e14981a on tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Subscribing to channel d01ab2a2a27ef9bf96d8084ff843ba3d6cb486b9 on tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Subscribing to channel 0fe18d4d454b7b4553062b622cd6e530465b5a89 on tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Subscribing to channel de39467be37caa5f6330e1993ec20f5b044c35eb on tcp://notifications.sparkleshare.org:443/

22:03:55 | Listener | Listening for announcements on tcp://notifications.sparkleshare.org:443/

22:04:53 | Fetcher | C:\Users\Dingane\SparkleShare\.tmp\COMP150-SP17-PSA8-Group27 | Fetching folder: ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA8-Group27

22:04:53 | Auth | Fetching host key for comp150.sandiego.edu

22:04:53 | Cmd | ssh-keyscan -t rsa -p 4499 comp150.sandiego.edu

22:04:54 | Auth | Skipping fingerprint check

22:04:54 | Cmd | .tmp | git clone --progress --no-checkout --depth=1 "ssh://git@comp150.sandiego.edu:4499/COMP150-SP17-PSA8-Group27" "C:\Users\Dingane\SparkleShare\.tmp\COMP150-SP17-PSA8-Group27"

22:04:56 | Fetcher | RSA host key for IP address '10.0.16.45' not in list of known hosts.

**Comment by hbons** [comment]
I remember this being fixed. Can't say when it will be out in a release though as the Windows needs some love.
